AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: EventBridge Lambda and MongoDB Atlas
Parameters:
  PartnerEventSource:
    Description: Name of Partner Event Source
    Type: String
    Default: aws.partner/mongodb.com/stitch.trigger/6606ca6a6c0a445929f109b0
Globals:
  Function:
    Timeout: 3
Resources:
  myeventfunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdafunction/
      Handler: reviewanalysis.lambda_handler
      Runtime: python3.12
      FunctionName: myeventfunction
      Policies:
        Statement:
            - Effect: Allow
              Action: comprehend:*
              Resource: "*"

    Metadata:
      SamResourceId: myeventfunction
  PartnerEventBus:
    Type: AWS::Events::EventBus
    Properties:
      EventSourceName:
        Ref: PartnerEventSource
      Name:
        Ref: PartnerEventSource
    Metadata:
      SamResourceId: PartnerEventBus
  myeventrule:
    Type: AWS::Events::Rule
    Properties:
      Description: Test Events Rule
      EventBusName:
        Ref: PartnerEventSource
      EventPattern:
        account:
        - Ref: AWS::AccountId
      Name: myeventrule
      State: ENABLED
      Targets:
      - Arn:
          Fn::GetAtt:
          - myeventfunction
          - Arn
        Id: idmyeventrule
    Metadata:
      SamResourceId: myeventrule
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: myeventfunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - myeventrule
        - Arn
    Metadata:
      SamResourceId: PermissionForEventsToInvokeLambda
